### ISSUE TITLE
Share experience with KFG

### ISSUE THREAD

**Issue by seekanddefine** [knowledge-for-good/knowledgeforgood#206]

**Comment by seekanddefine** [comment]
What is the best way to do this?

**Comment by seekanddefine** [comment]
@avidrucker what is the difference between having them as a markdown file rather than a comment in an issue?

**Comment by avidrucker** [comment]
> @avidrucker what is the difference between having them as a markdown file rather than a comment in an issue?

@seekanddefine Great question! Having a markdown file (versus a comment in an issue) allows for:
- simple sharing, b/c it can be:
    - linked to
    - downloaded
    - converted to other formats (PDF, etc.)
- faster finding
    - it's a file you can see on the home page
    - you can easily search for it
    - it won't be "closed" by or "hidden" in an issue (that might not necessarily have a clear name of what might be inside)
    - won't require scrolling through an issue
- trackable editing (we can see who edited it and when)
- better permission controls on who can edit (since comments & issues can be closed by more people, without a clear indication of why)
- increased engagement by collaborators b/c more people are likely see it when clearly shared as a file

**Comment by avidrucker** [comment]
Since you've already shared your feedback as a comment, I'd say that this issue isn't blocked per se, and is actually resolved. I'd encourage you to make a new issue regarding further questions, and link back here. Closing for now - as always, feel free to re-open as needed 👍🙂

**Comment by avidrucker** [comment]
Ps. @seekanddefine  Please update the time estimate label on this issue if writing and posting your feedback as a comment a different amount of time than currently marked. 🙇‍♂️🙇‍♂️🙇‍♂️
