### ISSUE TITLE
Linnea reads SRS Interactive Comic

### ISSUE THREAD

**Issue by avidrucker** [knowledge-for-good/knowledgeforgood#46]
Approx. time to do: 30 min
Value: High
Urgency: Low
Link: https://ncase.me/remember/
Why: This interactive comic is an example of what is called an "Explorable Explanation" which is basically an interactive medium that main contain things like animation, simulation, sound, video, and more. Nicky Case is one of my favorite creators, and I believe they are an incredible inspiration in this medium as well as an incredibly conscientious person in the digital creator space - basically, they are one of my heroes.

**Comment by seekanddefine** [comment]
@avidrucker I love this so much! In truth one of the reasons I ran a marathon was because of the writing from the creator of The Oatmeal [https://theoatmeal.com/comics/marathon_do.](https://theoatmeal.com/comics/marathon_do.)

Takeaways:

Learning can be evidenced-based and fun.

Anything you choose can be stored in long-term memory forever.

*   Q. What have you learned with spaced repetition? What are you learning with spaced repetition?

Lol: **use Spaced Repetition to learn about Spaced Repetition**

"It's a way to take back control of your _mind._ To make long-term memory a _choice_. To develop a lifelong love of learning..."

*   Q. How do we harness the power of spaced repetition in KFG?

I have wondered about applying this to my notetaking. Take notes on paper throughout the day. At the end of the day type notes into appropriate places. Then apply a rating system for what is most important to remember and recall based on increasing gaps. 

"you can easily keep _any number_ of things in your long-term memory, _FOREVER."_  
 

I really want to do this with my daughter!

"It's not about _collection_, it's about _connection_."

![](https://user-images.githubusercontent.com/38668794/126244753-788efb94-5da2-4b53-ab04-72c9e60ac371.png)

**Comment by avidrucker** [comment]
Changing the time to reflect the time to take and upload your awesome notes! Thank you for sharing them! 🙇‍♂️
