### ISSUE TITLE
Video recording experienced collaborator brainstorms recording stories

### ISSUE THREAD

**Issue by avidrucker** [knowledge-for-good/knowledgeforgood#85]
For example:
- Recorder person ("RP") captures their full cell phone screen & the phone's mic
- "RP" captures their full computer monitor & the built in mic
- "RP" captures multiple screens & external mic & composes them all together in software package X
- RP adds captions as external text file (SRT)
- RP writes best practices for different recording scenarios (for eg. no faces, and toggle-able captions so that way the screen real estate is maximized for, for eg. code, small intricate on-screen displays, etc.)

Stories = "use cases"

Tools List:
- Bloom
- Zoom
- Google Meet
- OBS

**Comment by seekanddefine** [comment]
## Ways to Record/User Stories

(Linnea feedback: I'm still a little confused about what exactly to do here, so here's what I've got so far in 30 min. Wow. The time went fast. )

Time 5:15-5:45pm 

Thoughts and Notes:

User Stories are part of Agile/Scrum and are used to describe the requirements to fit a sprint or product backlog. 

We are exploring application, interaction, and interfaces for recording our KFG process. What considerations needs to be taken in recording workplace meetings and conversations at work? 

In some business cases releasing video recordings is illegal. What consent needs to be documented?

Do the benefits of recording outweigh the nonlegal risks? Employers should draft, implement, and administer a consistent policy that doesn't interfere with NLRA employee rights. 

*   Q. How can video encourage productivity support team members best?
*   Q. What is the best way to manage video call recordings and notes?

## Template

<table><tbody><tr><td>Template</td><td>Describes</td></tr><tr><td>As a [stakeholder]</td><td>Who?</td></tr><tr><td>I want to [requirement]</td><td>What?</td></tr><tr><td>So that [motivation]</td><td>Why?</td></tr></tbody></table>

## Case 1: Mine

<table><tbody><tr><td>As a team member of KFG</td><td>Who?</td></tr><tr><td>I want to record and document our progress</td><td>What?</td></tr><tr><td>So that I can remember where we came from, keep track of details I need to come back to, and work transparently so that others can join asynchronously and contribute to our mission.&nbsp;</td><td>Why?</td></tr></tbody></table>

## Case 2: A Past Experience

Person to record is chosen at the beginning of the team call. They record with Loom built into GitHub). 

An agenda is found in Roam Research where anyone with the link can add text. Additional members are having casual conversation about the meeting topics in a Discord channel while the meeting is happening so that conversation and links are lost after the meeting ends.

Afterward the person who recorded uploads the video  and shares the link in Discord. (I think this is was done on youtube?)

Wow. The time went fast.

**Comment by avidrucker** [comment]
How about we break these questions out into individual issues and see where that leads us? I should note that I feel strongly about taking care to avoid harm, and also, am struggling to make enough time and attention in the day... This is a separate challenge of focus, time, and energy...
